FROM node:21-alpine AS builder

WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm ci && npm install --save-dev @nestjs/cli
COPY src ./src
COPY tsconfig.json tsconfig.build.json ./
ENV NODE_OPTIONS="--max-old-space-size=2048"
RUN npm run build

FROM node:21-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/dist ./dist
COPY package.json package-lock.json ./
RUN npm ci --production

EXPOSE 8000
CMD ["npm", "run", "start:prod"]