FROM node:21-alpine AS builder

WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm ci && npm install --save-dev @nestjs/cli
COPY . .
RUN npm run build

FROM node:21-alpine
WORKDIR /usr/src/app
RUN apk add --no-cache curl
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package.json ./

EXPOSE 8000
CMD ["npm", "run", "start:prod"]